---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: publish
    image: plugins/docker:20.13
    settings:
      tags:
       - latest
      dockerfile: docker/Dockerfile.linux.arm64
      repo: kameshsampath/kube-dev-tools
      dry_run: true
      purge: false