apiVersion: v1
data:
  # Add additonal hosts seperated by new-line
  registryAliases: >-
    dev.local
    ko.local
    example.com
  # default registry address in minikube
  registrySvc: registry.kube-system.svc.cluster.local
kind: ConfigMap
metadata:
  name: registry-aliases
  namespace: kube-system
