---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  labels:
    app.kubernetes.io/name: nexus3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus3
    spec:
      serviceAccountName: nexus
      securityContext:
        runAsUser: 200
        fsGroup: 200
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
      containers:
        - name: nexus
          image: docker.io/kameshsampath/nexus3:3.41.0-01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: 8081-tcp
          livenessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081-tcp
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081-tcp
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081-tcp
            failureThreshold: 6
            periodSeconds: 30
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data