apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus
subjects:
- kind: ServiceAccount
  name: nexus
  namespace: default
  apiGroup: ""
roleRef:
  kind: Role
  name: nexus
  apiGroup: rbac.authorization.k8s.io
