---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app.kubernetes.io/name: nexus3
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nexus3
  ports:
    - port: 8081
      nodePort: 30081
      targetPort: 8081-tcp